// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/promptly/promptly.d.ts
declare module "promptly" {
  import stream = require('stream');

  interface Callback {
    (err: Error, value: string): void;
  }

  export interface Options {
    default?: string;
    trim?: boolean;
    validator?: any;
    retry?: boolean;
    silent?: boolean;
    input?: NodeJS.ReadableStream;
    output?: NodeJS.WritableStream;
  }

  export function prompt(message: string, fn?: Callback):any;
  export function prompt(message: string, opts: Options, fn?: Callback):any;

  export function password(message: string, fn?: Callback):any;
  export function password(message: string, opts: Options, fn?: Callback):any;

  export function confirm(message: string, fn?: Callback):any;
  export function confirm(message: string, opts: Options, fn?: Callback):any;

  export function choose(message: string, choices: string[], fn?: Callback):any;
  export function choose(message: string, choices: string[], opts: Options, fn?: Callback):any;

}
