// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/4923ba548ae77ba4c5e18c17df40e6dda0c6e174/opener/index.d.ts
declare module 'opener' {
// Type definitions for opener 1.4
// Project: https://github.com/domenic/opener
// Definitions by: Rahul Ravikumar <https://github.com/tikurahul>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference types='node' />

import { ChildProcess } from 'child_process';

type Callback = (error: Error, stdout: string, stderr: string) => void;
function opener(
    args: string | string[], options?: {}, callback?: Callback): ChildProcess;

export = opener;
}
