// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/d581cd13ab2425f27373d4e220932ce9b26bd315/qs/index.d.ts
declare module 'qs' {
// Type definitions for qs 6.2.0
// Project: https://github.com/hapijs/qs
// Definitions by: Roman Korneev <https://github.com/RWander>, Leon Yu <https://github.com/leonyu>,
//     Belinda Teh <https://github.com/tehbelinda>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

namespace QueryString {
    export interface IStringifyOptions {
        delimiter?: string;
        strictNullHandling?: boolean;
        skipNulls?: boolean;
        encode?: boolean;
        encoder?: (str: string) => any;
        filter?: Array<string | number> | ((prefix: string, value: any) => any);
        arrayFormat?: 'indices' | 'brackets' | 'repeat';
        indices?: boolean;
        sort?: (a: any, b: any) => number;
    }

    export interface IParseOptions {
        delimiter?: string | RegExp;
        depth?: number;
        decoder?: (str: string) => any;
        arrayLimit?: number;
        parseArrays?: boolean;
        allowDots?: boolean;
        plainObjects?: boolean;
        allowPrototypes?: boolean;
        parameterLimit?: number;
        strictNullHandling?: boolean;
    }

    export function stringify(obj: any, options?: IStringifyOptions): string;
    export function parse(str: string, options?: IParseOptions): any;
}
export = QueryString;
}
