// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-wordwrap/c5852a5a23954e721246001d4bc47d19c283cd33/index.d.ts
declare module 'wordwrap' {
function wordwrap (options: wordwrap.Options): wordwrap.Wrap;
function wordwrap (stop: number, options?: wordwrap.Options): wordwrap.Wrap;
function wordwrap (start: number, stop: number, options?: wordwrap.Options): wordwrap.Wrap;

namespace wordwrap {
  export var soft: typeof wordwrap;
  export function hard (options: Options): Wrap;
  export function hard (stop: number, options: Options): Wrap;
  export function hard (start: number, stop: number): Wrap;

  export interface Options {
    start?: number;
    stop?: number;
    mode?: string;
    wrap?: string;
  }

  export interface Wrap {
    (value: string): string;
  }
}

export = wordwrap;
}
