trigger:
  branches:
    include:
    - master 

pr:
  branches:
    include:
    - '*'

variables: 
- name: API_TOKEN_KEY_VAULT
  value: 'distributionStoresInt'
- name: API_TOKEN_KEY_VAULT_AZURE_SUBSCRIPTION
  value: 'App Center - INT'

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

jobs:
- job: ConditionalJob
  steps:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - template: appcenter-cli-master-pipeline-template.yml

  - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - template: appcenter-cli-pr-pipeline-template.yml